name: Building Exilence-CE for Linux
on: [push]
jobs:
  build:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14.16.1
        cache: 'npm'
    - run: npm ci
    - run: npm run smoke-build-linux
    - uses: actions/upload-artifact@v3
      with:
        name: exilence-ce-win
        path: dist/Exilence*.exe
